# Generated by Django 5.0.7 on 2024-09-10 21:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0004_rename_timestamp_friendrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
